version: '3'

services:
  backend:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: 'pbid/url-shortner-backend'
    ports:
      - '4000:4000'
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: 'pbid/url-shortner-frontend'
    ports:
      - '3000:3000'
